# Runs cargo audit, an auditing tool for Rust. See https://github.com/rustsec/rustsec
name: Security Audit

# Only run this when dependencies change.
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
