name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  # Verifies that the formatting of the code conforms to the standard.
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

    - name: Check format
      run: cargo fmt --check --all

  # Ensures that there are no lint warnings or type errors.
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

    - name: Install Protobuf (needed by prost)
      run: |
        curl -fsSLO https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protoc-21.5-linux-x86_64.zip
        mkdir /tmp/protoc
        unzip protoc-*.zip -d /tmp/protoc
        rm protoc-*.zip
        chmod -R go+rX /tmp/protoc
        sudo mv /tmp/protoc/bin/protoc /usr/local/bin/
        sudo mv /tmp/protoc/include/* /usr/local/include/
        rm -r /tmp/protoc

    - name: Lint
      run: cargo clippy --workspace --all-targets -- --deny warnings

    # Ensures that the docs can be built properly.
    - name: Docs
      run: cargo doc --no-deps
      env:
        RUSTDOCFLAGS: -D warnings

  # Runs cargo deny, an auditing tool and dependency checker, among other things. See https://github.com/EmbarkStudios/cargo-deny
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

    - name: Audit
      uses: EmbarkStudios/cargo-deny-action@3f4a782664881cf5725d0ffd23969fcce89fd868

  # Runs the test suite and deploys if this was pushed to main.
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

    - name: Install Protobuf (needed by prost)
      run: |
        curl -fsSLO https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protoc-21.5-linux-x86_64.zip
        mkdir /tmp/protoc
        unzip protoc-*.zip -d /tmp/protoc
        rm protoc-*.zip
        chmod -R go+rX /tmp/protoc
        sudo mv /tmp/protoc/bin/protoc /usr/local/bin/
        sudo mv /tmp/protoc/include/* /usr/local/include/
        rm -r /tmp/protoc

    - name: Install just
      run: cargo install just

    - name: Run tests
      run: just test
