name: Format

on:
  pull_request:
  push:
    branches: main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check --all
