name: Test

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install just
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: just

    - name: Run tests
      run: just test
