name: Test

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Protobuf (needed by prost)
      run: |
        curl -fsSLO https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protoc-21.5-linux-x86_64.zip
        mkdir /tmp/protoc
        unzip protoc-*.zip -d /tmp/protoc
        rm protoc-*.zip
        chmod -R go+rX /tmp/protoc
        sudo mv /tmp/protoc/bin/protoc /usr/local/bin/
        sudo mv /tmp/protoc/include/* /usr/local/include/
        rm -r /tmp/protoc

    - name: Install just
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: just

    - name: Run tests
      run: just test
